### ISSUE TITLE
Mejorar Parser?

### ISSUE THREAD

**Issue by kshmir** [kshmir/so-2011#10]
http://codepad.org/dSHoocBj

Decime si eso no simplificaría infinitamente el parsing.

**Comment by kshmir** [comment]
Usé el parser en linux y tira un error en algún free.
Voy a ver de solucionarlo, pero no hay promesas.

> #0  0x0012e416 in __kernel_vsyscall ()
> #1  0x00172e71 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
> #2  0x0017634e in abort () at abort.c:92
> #3  0x001a9577 in __libc_message (do_abort=2, 
>     fmt=0x2828ac "**\* glibc detected **\* %s: %s: 0x%s ***\n")
>     at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
> #4  0x001b3961 in malloc_printerr (action=<value optimized out>, 
>     str=<value optimized out>, ptr=0x8055510) at malloc.c:6283
> #5  0x001b528b in _int_free (av=<value optimized out>, p=0x8055508) at malloc.c:4795
> #6  0x001b7001 in _int_realloc (av=<value optimized out>, oldp=0x8055508, oldsize=40, 
>     nb=48) at malloc.c:5341
> #7  0x001b8579 in __libc_realloc (oldmem=0x8055510, bytes=39) at malloc.c:3821
> #8  0x080500a8 in cstring_expand (s=0x8055510 "\nCaramelos 2000\n\nAndorra Peru 30\n\n", 
>     extraSize=4) at src/utils/cstring.c:69
> #9  0x080500ff in cstring_write (
>     original=0x8055510 "\nCaramelos 2000\n\nAndorra Peru 30\n\n", 
>     to_append=0x8054f48 "Peru") at src/utils/cstring.c:82
> #10 0x08049949 in sim_level_serialize (level=0x8054ac0)
>     at src/tps/tp1/core/sim_level.c:44
> #11 0x0804d3d1 in serializing_test () at src/tps/tp1/tp1_test.c:168
> #12 0x0804d4e3 in main (argc=1, params=0xbffff904) at src/tps/tp1/tp1_test.c:187
